USE SYNTHETIC_BANKING;

SELECT DISTINCT(TRANSACTION_DATE) FROM TRANSACTIONS WHERE TRANSACTION_DATE IS NULL;

UPDATE CUSTOMERS
SET CREDIT_SCORE=0 WHERE CREDIT_SCORE IS NULL OR CREDIT_SCORE<0;



UPDATE CUSTOMERS
SET FIRST_NAME=LAST_NAME WHERE FIRST_NAME IS NULL;

UPDATE ACCOUNTS
SET BALANCE_USD=0 WHERE BALANCE_USD IS NULL;

UPDATE BRANCHES
SET MANAGER_NAME='Unknown' WHERE MANAGER_NAME IS NULL;

UPDATE CARDS
SET EXPIRATION_DATE=CURDATE() WHERE EXPIRATION_DATE IS NULL;

UPDATE LOANS
SET LOAN_AMOUNT=0 WHERE LOAN_AMOUNT<0;

SET @avg=(SELECT AVG(INTEREST_RATE) FROM LOANS);
UPDATE LOANS
SET INTEREST_RATE=@avg WHERE INTEREST_RATE IS NULL;

SET @m_name=(SELECT MERCHANT_NAME FROM MERCHANTS GROUP BY MERCHANT_NAME HAVING COUNT(*)=(SELECT MAX(TOTAL) FROM (SELECT COUNT(*) AS TOTAL, MERCHANT_NAME FROM MERCHANTS GROUP BY MERCHANT_NAME) T
) LIMIT 1);

UPDATE MERCHANTS
SET MERCHANT_NAME=@m_name
WHERE MERCHANT_NAME IS NULL;

UPDATE TRANSACTIONS
SET AMOUNT_USD=0
WHERE AMOUNT_USD<0;

SELECT * FROM TRANSACTIONS LIMIT 10;
SELECT COUNT(*) FROM CUSTOMERS GROUP BY CUSTOMER_ID,FIRST_NAME,LAST_NAME,EMAIL,CITY,CREDIT_SCORE,CREATED_AT HAVING COUNT(*)>1;
SELECT COUNT(*) FROM ACCOUNTS GROUP BY ACCOUNT_ID,CUSTOMER_ID,ACCOUNT_TYPE, BALANCE_USD,OPEN_DATE HAVING COUNT(*)>1;
SELECT COUNT(*) FROM BRANCHES GROUP BY BRANCH_NAME,MANAGER_NAME,CITY,COUNTRY HAVING COUNT(*)>1;
SELECT COUNT(*) FROM CARDS GROUP BY CARD_ID,ACCOUNT_ID,CARD_TYPE,EXPIRATION_DATE HAVING COUNT(*)>1;
SELECT COUNT(*) FROM LOANS GROUP BY CUSTOMER_ID,LOAN_AMOUNT,INTEREST_RATE,START_DATE HAVING COUNT(*)>1;
SELECT COUNT(*) FROM MERCHANTS GROUP BY MERCHANT_NAME,CITY HAVING COUNT(*)>1;
SELECT COUNT(*) FROM TRANSACTIONS GROUP BY TRANSACTION_ID,ACCOUNT_ID,MERCHANT_ID,AMOUNT_USD,TRANSACTION_DATE HAVING COUNT(*)>1;

ALTER TABLE TRANSACTIONS
ADD COLUMN TRANSACTION_TIME TIME AFTER TRANSACTION_DATE;

UPDATE TRANSACTIONS
SET TRANSACTION_TIME=SUBSTRING_INDEX(TRANSACTION_DATE,' ',-1);

ALTER TABLE TRANSACTIONS MODIFY COLUMN TRANSACTION_DATE DATE;

UPDATE TRANSACTIONS
SET TRANSACTION_DATE=REPLACE(TRANSACTION_DATE,SUBSTRING_INDEX(TRANSACTION_DATE,' ',-1),'');

ALTER TABLE CUSTOMERS
ADD COLUMN CREATED_TIME TIME AFTER CREATED_AT;

UPDATE CUSTOMERS
SET CREATED_TIME=SUBSTRING_INDEX(CREATED_AT,' ',-1);
SELECT * FROM TRANSACTIONS;

UPDATE CUSTOMERS
SET CREATED_AT=REPLACE(CREATED_AT,SUBSTRING_INDEX(CREATED_AT,' ',-1),'');

ALTER TABLE CUSTOMERS MODIFY COLUMN CREATED_AT DATE;


UPDATE BRANCHES
SET BRANCH_NAME=REPLACE(BRANCH_NAME,'Branch','');

select * from customers;
ALTER TABLE CUSTOMERS ADD COLUMN name_person VARCHAR(255) FIRST;
ALTER TABLE CUSTOMERS DROP COLUMN NAME;
ALTER TABLE CUSTOMERS DROP COLUMN FIRST_NAME,DROP COLUMN LAST_NAME;
UPDATE CUSTOMERS
SET NAME=CONCAT(FIRST_NAME,' ',LAST_NAME);

UPDATE CUSTOMERS
SET NAME_PERSON=NAME;


-- CUSTOMERS HOLDS WHICH TYPE OF CARD
select A.ACCOUNT_ID,CONCAT(CS.FIRST_NAME,' ',CS.LAST_NAME) AS NAME,C.CARD_TYPE from accounts A
JOIN CARDS C 
ON A.ACCOUNT_ID=C.ACCOUNT_ID
JOIN CUSTOMERS CS
ON A.CUSTOMER_ID=CS.CUSTOMER_ID;

-- TOTAL NO OF CUSTOMERS HOLDING CARDS CATEGORTY WISE
-- AFTER CREATING INDEX, QUERY EXECUTION TIME REDUCED FROM 1.984 S TO 1.813S
CREATE INDEX IDX_CUSTOMERS_ID ON CUSTOMERS(CUSTOMER_ID);
CREATE INDEX IDX_ACCOUNTS_ID ON ACCOUNTS(ACCOUNT_ID);
select C.CARD_TYPE, COUNT(*) from accounts A
JOIN CARDS C 
ON A.ACCOUNT_ID=C.ACCOUNT_ID
JOIN CUSTOMERS CS
ON A.CUSTOMER_ID=CS.CUSTOMER_ID
GROUP BY C.CARD_TYPE;

-- top customers who has done most transactions
CREATE INDEX idx_acc_id 
ON transactions(account_id);
SELECT A.ACCOUNT_ID,C.NAME_PERSON,T.TOTAL_AMOUNT,dense_rank() OVER(ORDER BY TOTAL_AMOUNT DESC) AS "RANK" FROM ACCOUNTS A
JOIN CUSTOMERS C
ON A.CUSTOMER_ID=C.CUSTOMER_ID
JOIN (
   SELECT ACCOUNT_ID,SUM(AMOUNT_USD) AS TOTAL_AMOUNT FROM TRANSACTIONS GROUP BY ACCOUNT_ID
) T
ON A.ACCOUNT_ID=T.ACCOUNT_ID;

-- CUSTOMERS WHOSE CREDIT SCORE>AVG CREDIT SCORE
ALTER TABLE CUSTOMERS ADD COLUMN CATEGORY VARCHAR(255);
SET @AVG_VALUE=(SELECT AVG(CREDIT_SCORE) FROM CUSTOMERS);
UPDATE CUSTOMERS
SET CATEGORY= CASE WHEN CREDIT_SCORE>@AVG_VALUE THEN 'PREMIUM'
			  ELSE 'REGULAR'
              END;
     

 
SELECT CUSTOMER_ID,NAME_PERSON,
SUM(CREDIT_SCORE) FROM CUSTOMERS
WHERE CREDIT_SCORE>(SELECT AVG(CREDIT_SCORE) FROM CUSTOMERS) 
GROUP BY CUSTOMER_ID;

-- customers who had taken loan recently
CREATE VIEW RANKED_LOANDATA AS 
SELECT CUSTOMER_ID,DIFFERENCE,DENSE_RANK() OVER(ORDER BY T.DIFFERENCE) AS "SERIAL_NO" FROM (
SELECT CUSTOMER_ID,DATE_DIFF(START_DATE) AS DIFFERENCE 
FROM LOANS GROUP BY START_DATE,CUSTOMER_ID) T;
SELECT * FROM RANKED_LOANDATA;

SELECT C.NAME_PERSON,C.CUSTOMER_ID, P.SERIAL_NO FROM CUSTOMERS C JOIN
 RANKED_LOANDATA P
ON P.CUSTOMER_ID=C.CUSTOMER_ID LIMIT 1;

-- percent of transactions done by each customer
set @total=(SELECT SUM(AMOUNT_USD) FROM TRANSACTIONS);
SELECT T.ACCOUNT_ID,ROUND((T.PART/@TOTAL)*100,2) AS PERCENT 
FROM(SELECT ACCOUNT_ID,SUM(AMOUNT_USD) AS PART 
FROM TRANSACTIONS GROUP BY ACCOUNT_ID) t; 

-- inactive accounts
CREATE VIEW INACTIVE_ACCOUNT AS 
SELECT A.ACCOUNT_ID,DATE_DIFF(MAX(T.TRANSACTION_DATE)) AS DIFFERENCE FROM ACCOUNTS A
LEFT JOIN TRANSACTIONS T
ON T.ACCOUNT_ID=A.ACCOUNT_ID
GROUP BY A.ACCOUNT_ID
HAVING MAX(T.TRANSACTION_DATE) IS NULL OR
DATE_DIFF(MAX(T.TRANSACTION_DATE))>30;

SELECT * FROM INACTIVE_ACCOUNT;

-- AVG TRANSACTION DONE PER USER PER TRANSACTION DATE GROUP IN LAST 7 DAYS
SELECT ACCOUNT_ID,AVG(AMOUNT_USD) 
OVER(PARTITION BY ACCOUNT_ID 
ORDER BY TRANSACTION_DATE ROWS BETWEEN 7 preceding AND CURRENT ROW) AS "RECENT TRANSACTIONS" FROM TRANSACTIONS;

-- CUSTOMER WHO USE EITHER CREDIT CARD OR DEBIT CARD BUT NOT BOTH
SELECT A.ACCOUNT_ID,A.ACCOUNT_TYPE,C.NAME_PERSON FROM ACCOUNTS A JOIN (SELECT ACCOUNT_ID FROM CARDS
GROUP BY ACCOUNT_ID
HAVING COUNT(DISTINCT(CARD_TYPE))=1) B 
ON A.ACCOUNT_ID=B.ACCOUNT_ID
JOIN CUSTOMERS C
ON C.CUSTOMER_ID=A.CUSTOMER_ID;

CREATE VIEW MERCHANT_TRANSACTION AS 
SELECT ACCOUNT_ID FROM MERCHANTS M
JOIN TRANSACTIONS T
ON M.MERCHANT_ID=T.MERCHANT_ID GROUP BY ACCOUNT_ID;
-- customer category based on balance
SELECT ACCOUNT_ID, CUSTOMER_CATEGORY(ACCOUNT_ID) AS CATEGORY FROM ACCOUNTS;

-- CUSTOMERS WHO'S CARD HAS BEEN EXPIRED
SELECT A.ACCOUNT_ID,CS.NAME_PERSON,EXPIRED(C.EXPIRATION_DATE) AS EXPIRED FROM CARDS C 
JOIN ACCOUNTS A ON
C.ACCOUNT_ID=A.ACCOUNT_ID
JOIN CUSTOMERS CS
ON CS.CUSTOMER_ID=A.CUSTOMER_ID;
;
-- TRANSACTION DONE FROM  ACCOUNT 1 TO 2
SET @MESSAGE='';
CALL BALANCE_TRANSFER('A002','A004',1000,@MESSAGE);
SELECT @MESSAGE;

-- MOST SPENDING CUSTOMERS
WITH total_spending as (
SELECT ACCOUNT_ID,SUM(AMOUNT_USD) AS TOTAL_AMOUNT,COUNT(TRANSACTION_ID) AS TOTAL_COUNT
FROM TRANSACTIONS 
GROUP BY ACCOUNT_ID),
AVG_DATA AS (SELECT AVG(TOTAL_AMOUNT) AS AVERAGE_AMOUNT,AVG(TOTAL_COUNT) AS AVERAGE_TRANSACTION FROM TOTAL_SPENDING)

SELECT T.ACCOUNT_ID,T.TOTAL_AMOUNT,T.TOTAL_COUNT FROM TOTAL_SPENDING T CROSS JOIN AVG_DATA A
WHERE T.TOTAL_AMOUNT>A.AVERAGE_AMOUNT AND T.TOTAL_COUNT>A.AVERAGE_TRANSACTION LIMIT 1;

-- SEGMENTING CUSTOMERS BASED ON TRANSACTION HISTORY
WITH total_spending as (
SELECT ACCOUNT_ID,SUM(AMOUNT_USD) AS TOTAL_AMOUNT,COUNT(TRANSACTION_ID) AS TOTAL_COUNT
FROM TRANSACTIONS 
GROUP BY ACCOUNT_ID),
DISTRIBUTED AS(
SELECT *,NTILE(10) OVER(ORDER BY TOTAL_AMOUNT DESC) AS DISTRIBUTED_DATA FROM TOTAL_SPENDING
)
SELECT CATEGORY,COUNT(*) FROM (SELECT ACCOUNT_ID,TOTAL_AMOUNT,
CASE  
   WHEN DISTRIBUTED_DATA=1 THEN 'TOP 10%'
   WHEN DISTRIBUTED_DATA BETWEEN 2 AND 5 THEN 'MIDDLE 40%'
   ELSE "BOTTOM 50%"
END AS CATEGORY 
FROM DISTRIBUTED) T GROUP BY CATEGORY;





















