-- head,tail and sample
SELECT * FROM laptopDATA
ORDER BY ID LIMIT 5;

SELECT * FROM laptopDATA
ORDER BY ID DESC LIMIT 5;

SELECT * FROM laptopDATA
ORDER BY rand() LIMIT 5;

SELECT COUNT(PRICE), MIN(PRICE),MAX(PRICE),AVG(PRICE),STD(PRICE),PERCENTILE_CONT(0.25) WITHIN GROUP(ORDER BY(PRICE) OVER() AS 'Q1',
 

