USE PRACTICE;
CREATE TABLE LAPTOPS_BACKUP LIKE LAPTOPDATA;
INSERT INTO LAPTOPS_BACKUP
SELECT * FROM LAPTOPDATA;

SELECT COUNT(*) FROM LAPTOPDATA;

SELECT * FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA='PRACTICE'
AND TABLE_NAME='LAPTOPDATA';

ALTER TABLE LAPTOPDATA DROP COLUMN `UNNAMED: 0`;
SELECT * FROM LAPTOPDATA;

DELETE FROM LAPTOPDATA 
WHERE ID NOT IN (
    SELECT * FROM (
        SELECT MIN(ID)
        FROM LAPTOPDATA
        GROUP BY COMPANY,TYPENAME,INCHES,SCREENRESOLUTION,CPU,RAM,MEMORY,GPU,OPSYS,WEIGHT,PRICE
    ) AS temp
);

SELECT DISTINCT(TYPENAME) FROM LAPTOPDATA;

ALTER TABLE LAPTOPDATA MODIFY COLUMN INCHES DECIMAL(10,1);

UPDATE LAPTOPDATA
SET RAM = REPLACE(RAM, 'GB', '');

ALTER TABLE LAPTOPDATA MODIFY COLUMN RAM INTEGER;

UPDATE LAPTOPDATA
SET WEIGHT= REPLACE(WEIGHT, 'kg', '');

ALTER TABLE LAPTOPDATA MODIFY COLUMN WEIGHT DECIMAL(10,1) ;

UPDATE LAPTOPDATA
SET WEIGHT=NULL WHERE WEIGHT='?' ;

SET @avg = (
    SELECT AVG(WEIGHT)
    FROM LAPTOPDATA
    WHERE WEIGHT IS NOT NULL
);

UPDATE LAPTOPDATA
SET WEIGHT=@avg WHERE WEIGHT is NULL ;

UPDATE LAPTOPDATA
SET PRICE=ROUND(PRICE);

ALTER TABLE LAPTOPDATA MODIFY COLUMN PRICE INTEGER;

SELECT DISTINCT(OPSYS) FROM LAPTOPDATA;

SELECT OPSYS,
CASE
  WHEN OPSYS LIKE '%mac%' THEN 'macos'
  WHEN OPSYS LIKE 'windows%' THEN 'windows'
  WHEN OPSYS LIKE '%linux%' THEN 'linux'
  WHEN OPSYS='No OS' THEN 'N/A'
  ELSE 'other'
END AS 'os_brand'
FROM LAPTOPDATA;

UPDATE LAPTOPDATA
SET OPSYS=CASE
  WHEN OPSYS LIKE '%mac%' THEN 'macos'
  WHEN OPSYS LIKE 'windows%' THEN 'windows'
  WHEN OPSYS LIKE '%linux%' THEN 'linux'
  WHEN OPSYS='No OS' THEN 'N/A'
  ELSE 'other'
END;

ALTER TABLE LAPTOPDATA
ADD COLUMN GPU_BRAND VARCHAR(255) AFTER GPU,
ADD COLUMN GPU_NAME VARCHAR(255) AFTER GPU_BRAND;


UPDATE LAPTOPDATA
SET GPU_BRAND=SUBSTRING_INDEX(GPU,' ',1);

UPDATE LAPTOPDATA 
SET GPU_NAME=REPLACE(GPU,GPU_BRAND,'');


ALTER TABLE LAPTOPDATA DROP COLUMN GPU;

ALTER TABLE LAPTOPDATA
ADD COLUMN CPU_BRAND VARCHAR(255) AFTER cPU,
ADD COLUMN CPU_NAME VARCHAR(255) AFTER CPU_BRAND,
ADD COLUMN CPU_SPEED DECIMAL(10,1) AFTER CPU_NAME;

UPDATE LAPTOPDATA 
SET CPU_BRAND=SUBSTRING_INDEX(CPU,' ',1);

UPDATE LAPTOPDATA 
SET CPU_SPEED=CAST(REPLACE(SUBSTRING_INDEX(CPU,' ',-1),'GHz','') AS DECIMAL(10,2));

UPDATE LAPTOPDATA
SET CPU_NAME=REPLACE(REPLACE(CPU,CPU_BRAND,''),SUBSTRING_INDEX(REPLACE(CPU,CPU_BRAND,''),' ',-1),'');

ALTER TABLE LAPTOPDATA DROP COLUMN CPU;

SELECT SCREENRESOLUTION, 
SUBSTRING_INDEX(SUBSTRING_INDEX(SCREENRESOLUTION,' ',-1),'x',1),
SUBSTRING_INDEX(SUBSTRING_INDEX(SCREENRESOLUTION,' ',-1),'x',-1)
 from laptopdata;
 
ALTER TABLE LAPTOPDATA
ADD COLUMN RESOLUTION_WIDTH INTEGER AFTER SCREENRESOLUTION,
ADD COLUMN RESOLUTION_HEIGHT INTEGER AFTER RESOLUTION_WIDTH;

UPDATE LAPTOPDATA
SET RESOLUTION_WIDTH=SUBSTRING_INDEX(SUBSTRING_INDEX(SCREENRESOLUTION,' ',-1),'x',1),
RESOLUTION_HEIGHT=SUBSTRING_INDEX(SUBSTRING_INDEX(SCREENRESOLUTION,' ',-1),'x',-1);

ALTER TABLE LAPTOPDATA
ADD COLUMN TOUCHSCREEN INTEGER AFTER RESOLUTION_HEIGHT;

UPDATE LAPTOPDATA
SET TOUCHSCREEN=SCREENRESOLUTION LIKE '%Touch%';

ALTER TABLE LAPTOPDATA
DROP COLUMN SCREENRESOLUTION;

UPDATE LAPTOPDATA
SET CPU_NAME=SUBSTRING_INDEX(TRIM(CPU_NAME),' ',2);

ALTER TABLE LAPTOPDATA
ADD COLUMN MEMORY_TYPE VARCHAR(255) AFTER MEMORY,
ADD COLUMN PRIMARY_STORAGE INTEGER AFTER MEMORY_TYPE,
ADD COLUMN SECONDARY_STORAGE INTEGER AFTER PRIMARY_STORAGE;

SELECT MEMORY,
CASE 
   WHEN MEMORY LIKE '%SSD%' AND MEMORY LIKE '%HDD%' THEN 'Hybrid'
   WHEN MEMORY LIKE '%SSD%' THEN 'SSD'
   WHEN MEMORY LIKE '%HDD%' THEN 'HDD'
   WHEN MEMORY LIKE '%Flash Storage%' THEN 'Flash Storage'
   WHEN MEMORY LIKE '%Hybrid%' THEN 'Hybrid'
   WHEN MEMORY LIKE '%Flash Storage%' AND Memory Like '%HDD%' THEN 'Hybrid'
   ELSE null
END AS 'MEMORY_TYPE'
FROM LAPTOPDATA;

UPDATE LAPTOPDATA
SET MEMORY_TYPE=CASE 
   WHEN MEMORY LIKE '%SSD%' AND MEMORY LIKE '%HDD%' THEN 'Hybrid'
   WHEN MEMORY LIKE '%SSD%' THEN 'SSD'
   WHEN MEMORY LIKE '%HDD%' THEN 'HDD'
   WHEN MEMORY LIKE '%Flash Storage%' THEN 'Flash Storage'
   WHEN MEMORY LIKE '%Hybrid%' THEN 'Hybrid'
   WHEN MEMORY LIKE '%Flash Storage%' AND Memory Like '%HDD%' THEN 'Hybrid'
   ELSE null
END;

SELECT MEMORY,
REGEXP_SUBSTR(SUBSTRING_INDEX(MEMORY,'+',1),'[0-9]+'),
CASE WHEN MEMORY LIKE '%+%' THEN REGEXP_SUBSTR(SUBSTRING_INDEX(MEMORY,'+',-1),'[0-9]+') ELSE 0 END
FROM LAPTOPDATA;

UPDATE LAPTOPDATA
SET PRIMARY_STORAGE=REGEXP_SUBSTR(SUBSTRING_INDEX(MEMORY,'+',1),'[0-9]+'),
SECONDARY_STORAGE=CASE WHEN MEMORY LIKE '%+%' THEN REGEXP_SUBSTR(SUBSTRING_INDEX(MEMORY,'+',-1),'[0-9]+') ELSE 0 END
;

SELECT PRIMARY_STORAGE,
CASE WHEN PRIMARY_STORAGE<=2 THEN PRIMARY_STORAGE*1024 ELSE PRIMARY_STORAGE END,
SECONDARY_STORAGE,
CASE WHEN SECONDARY_STORAGE<=2 THEN SECONDARY_STORAGE*1024 ELSE SECONDARY_STORAGE END
FROM LAPTOPDATA;

UPDATE LAPTOPDATA
SET PRIMARY_STORAGE=CASE WHEN PRIMARY_STORAGE<=2 THEN PRIMARY_STORAGE*1024 ELSE PRIMARY_STORAGE END,
SECONDARY_STORAGE=CASE WHEN SECONDARY_STORAGE<=2 THEN SECONDARY_STORAGE*1024 ELSE SECONDARY_STORAGE END;

ALTER TABLE LAPTOPDATA DROP COLUMN MEMORY;
ALTER TABLE LAPTOPDATA DROP COLUMN GPU_NAME;




















SELECT * FROM LAPTOPDATA;















