USE SCHOOL;

CREATE TABLE marks (
 student_id INTEGER PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(255),
    branch VARCHAR(255),
    marks INTEGER
);

INSERT INTO marks (name,branch,marks)VALUES 
('Nitish','EEE',82),
('Rishabh','EEE',91),
('Anukant','EEE',69),
('Rupesh','EEE',55),
('Shubham','CSE',78),
('Ved','CSE',43),
('Deepak','CSE',98),
('Arpan','CSE',95),
('Vinay','ECE',95),
('Ankit','ECE',88),
('Anand','ECE',81),
('Rohit','ECE',95),
('Prashant','MECH',75),
('Amit','MECH',69),
('Sunny','MECH',39),
('Gautam','MECH',51);

-- FIND ALL THE STUDENTS WHO HAVE MARKS HIGHER THAN THE AVG MARKS OF THEIR RESPECTIVE BRANCH
SELECT * FROM(SELECT *, AVG(MARKS) OVER(PARTITION BY BRANCH) AS 'BRANCH_AVG' FROM MARKS) T
WHERE T.MARKS>T.BRANCH_AVG;

SELECT *, RANK() OVER(PARTITION BY BRANCH ORDER BY MARKS DESC), 
DENSE_RANK() OVER(PARTITION BY BRANCH ORDER BY MARKS DESC)
FROM MARKS;

SELECT *, CONCAT(BRANCH,'-',ROW_NUMBER() OVER(PARTITION BY BRANCH)) FROM MARKS;

-- TOP 2 MOST PAYING CUSTOMERS OF EACH MONTH
CREATE DATABASE ZOMATO;
USE ZOMATO;
SELECT * FROM (SELECT MONTH(DATE) AS MONTH_NUM,
       MONTHNAME(DATE) AS MONTH_NAME,
       USER_ID,
       SUM(AMOUNT) AS TOTAL,
       RANK() OVER(PARTITION BY MONTHNAME(DATE) ORDER BY SUM(AMOUNT) DESC) AS MONTH_RANK
FROM ORDERS
GROUP BY MONTHNAME(DATE),MONTH_NUM, USER_ID
ORDER BY MONTH_NUM) T 
WHERE T.MONTH_RANK<3
ORDER BY MONTH_NAME DESC, MONTH_RANK ASC;

USE SCHOOL;
SELECT *, FIRST_VALUE(NAME) OVER(ORDER BY MARKS DESC) FROM MARKS;
SELECT *, LAST_VALUE(NAME) OVER(PARTITION BY BRANCH ORDER BY MARKS DESC 
ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) FROM MARKS;

SELECT *, NTH_VALUE(NAME,2) OVER(PARTITION BY BRANCH ORDER BY MARKS DESC 
ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) FROM MARKS;

-- BRANCH TOPPERS
SELECT NAME,BRANCH,MARKS FROM (SELECT *,FIRST_VALUE(NAME) OVER(PARTITION BY BRANCH ORDER BY MARKS DESC) AS 'TOPPER_NAME',
FIRST_VALUE(MARKS) OVER(PARTITION BY BRANCH ORDER BY MARKS DESC) AS 'TOPPER_MARKS'
FROM MARKS) T
WHERE T.NAME=T.TOPPER_NAME AND T.MARKS=T.TOPPER_MARKS;

SELECT NAME,BRANCH,MARKS FROM (SELECT *,LAST_VALUE(NAME) OVER(PARTITION BY BRANCH ORDER BY MARKS DESC ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS 'TOPPER_NAME',
LAST_VALUE(MARKS) OVER(PARTITION BY BRANCH ORDER BY MARKS DESC ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS 'TOPPER_MARKS'
FROM MARKS) T
WHERE T.NAME=T.TOPPER_NAME AND T.MARKS=T.TOPPER_MARKS;

SELECT *,LAG(MARKS) OVER(PARTITION BY BRANCH ORDER BY STUDENT_ID),
LEAD(MARKS) OVER(PARTITION BY BRANCH ORDER BY STUDENT_ID) FROM MARKS;

-- MoM REVENUE GROWTH OF ZOMATO
USE ZOMATO;
SELECT MONTH(DATE) AS 'month_num',MONTHNAME(DATE),SUM(AMOUNT),((SUM(AMOUNT)-
LAG(SUM(AMOUNT)) OVER(ORDER BY MONTH(DATE)))/LAG(SUM(AMOUNT)) OVER(ORDER BY MONTH(DATE)))*100
FROM ORDERS
GROUP BY MONTHNAME(DATE),month_num
ORDER BY month_num ASC;

select count(*) from deliveries;

USE SCHOOL;
CREATE VIEW INDIGO AS 
SELECT * FROM FLIGHTS_CLEANED WHERE AIRLINE='Indigo Airline';

select * from indigo;
USE ZOMATO;

CREATE VIEW JOINED_ORDER_DATA AS
SELECT ORDER_ID,AMOUNT,R_NAME,NAME,DATE,DELIVERY_TIME,DELIVERY_RATING,RESTAURANT_RATING FROM ORDERS T1
JOIN USERS T2 ON T1.USER_ID=T2.USER_ID
JOIN RESTAURANTS T3 ON T1.R_ID=T3.R_ID;
DELETE FROM JOINED_ORDER_DATA WHERE ORDER_ID=1001;
SELECT R_NAME,MONTHNAME(DATE),MONTH(DATE),SUM(AMOUNT) FROM JOINED_ORDER_DATA GROUP BY R_NAME, MONTH(DATE),MONTHNAME(DATE);

UPDATE FLIGHTS_CLEANED SET AIRLINE='Indigo Airline'
WHERE AIRLINE='Indigo';

UPDATE INDIGO SET DESTINATION='DELHI'
WHERE DESTINATION='New Delhi';
SELECT * FROM FLIGHTS_CLEANED WHERE AIRLINE="Indigo Airline6`";

SELECT HELLO_WORLD();

SELECT CALCULATE_AGE('2000-10-10');

DROP TABLE IF EXISTS persons;

CREATE TABLE persons (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    dob DATE NOT NULL,
    gender ENUM('Male', 'Female', 'Other') NOT NULL,
    married CHAR(1) CHECK (married IN ('Y', 'N'))
);
INSERT INTO persons (name, dob, gender, married)
VALUES
('Rahul Sharma', '2000-05-15', 'Male', 'N'),
('Priya Patel', '1995-08-22', 'Female', 'Y'),
('Amit Shah', '1988-03-10', 'Male', 'Y'),
('Neha Verma', '2001-11-30', 'Female', 'N');

UPDATE PERSONS
SET NAME=LOWER(NAME);

SELECT *, PROPER_NAME(NAME,GENDER,MARRIED) FROM PERSONS;

SELECT * ,FORMAT_DATE(DATE_OF_JOURNEY) FROM flights_cleaned;

select *, format_date(dob) from persons;
 
SELECT FLIGHTS_BETWEEN('Banglore','Nflights_betweenew Delhi');

select * from flights_cleaned;

-- STORED PROCEDURE
CALL HELLO_WORLD();

SET @MESSAGE='';
CALL ADD_USER('Ankit','XYZ@gmail.com',@MESSAGE);
select * from users;

SELECT @MESSAGE;

CALL USER_ORDERS('vartika@gmail.com');

SET @TOTAL=0;
CALL PLACE_ORDER(3,3,'6,7',@TOTAL);

select @total;
select * from orders;

-- TRANSACTIONS
USE SCHOOL;
SELECT * FROM PERSONS;
ALTER TABLE PERSONS ADD COLUMN BALANCE INTEGER;
UPDATE persons SET balance = 10000 WHERE id = 1;
UPDATE persons SET balance = 20000 WHERE id = 2;
UPDATE persons SET balance = 30000 WHERE id = 3;
UPDATE persons SET balance = 40000 WHERE id = 4;

START TRANSACTION;
UPDATE persons SET balance = 40000 WHERE id = 1;
UPDATE persons SET balance = 35000 WHERE id = 4;
COMMIT;

START TRANSACTION;
UPDATE persons SET balance = 40000 WHERE id = 1;
UPDATE persons SET balance = 35000 WHERE id = 4;
ROLLBACK;


START TRANSACTION;
SAVEPOINT A;
UPDATE persons SET balance = 50000 WHERE id = 1;
SAVEPOINT B;
UPDATE persons SET balance = 35000 WHERE id = 4;
ROLLBACK TO B;

START TRANSACTION;
UPDATE persons SET balance = 40000 WHERE id = 1;
COMMIT;
UPDATE persons SET balance = 35000 WHERE id = 4;
ROLLBACK;
SELECT * FROM PERSONS;











